import json, os, re, time, uuid, hashlib, sqlite3
from pathlib import Path
from typing import Any, Callable, Dict, Optional

ROOT = Path(os.getenv('AI_INFINITY_DATA_DIR','/tmp/ai-infinity')) / 'studio_os'
ROOT.mkdir(parents=True, exist_ok=True)
DB = ROOT / 'studio.db'

def _db():
    c=sqlite3.connect(DB); c.row_factory=sqlite3.Row
    c.execute('CREATE TABLE IF NOT EXISTS studio_jobs(job_id TEXT PRIMARY KEY, status TEXT, payload TEXT, result TEXT, created REAL, updated REAL)')
    c.execute('CREATE TABLE IF NOT EXISTS studio_skills(skill_id TEXT PRIMARY KEY, name TEXT, version INTEGER, recipe TEXT, success REAL, uses INTEGER, updated REAL)')
    c.commit(); return c

def _uid(p='job'): return f'{p}_{uuid.uuid4().hex}'
def _json(x): return json.dumps(x,ensure_ascii=False)
def _clean_json(s):
    m=re.search(r'\{.*\}',str(s),re.S)
    return json.loads(m.group(0) if m else s)

def _default_strategy(topic, objective, fmt, audience, tone):
    return {
      'creative_direction': f'Create an original, authoritative, cinematic piece about {topic}. Every section must earn its place.',
      'hook_options':[f'The part of {topic} most people miss',f'What changes when you understand {topic}',f'{topic}: the useful truth in minutes'],
      'chapters':[{'title':'Hook','purpose':'immediate curiosity and promise'}, {'title':'Context','purpose':'establish what matters'}, {'title':'Deep Dive','purpose':'explain the core idea with concrete examples'}, {'title':'Implications','purpose':'show why the viewer should care'}, {'title':'Takeaway','purpose':'give an actionable conclusion'}],
      'visual_language':'cinematic documentary, purposeful motion, varied shot scale, clean typography, no generic filler',
      'sound_direction':'natural narration, restrained original score, strong transitions, clean dialogue mix',
      'editing_direction':'pattern interrupts, visual changes every few seconds, motivated cuts, readable captions',
      'quality_gates':['factual accuracy','originality','visual relevance','audio clarity','pacing','copyright/source traceability'],
      'audience':audience,'tone':tone,'format':fmt,'objective':objective
    }

def plan(topic, objective, fmt, duration, audience, tone, model_fn=None):
    if model_fn:
        prompt=f'''Act as a senior documentary/YouTube creative director and showrunner. Build a production blueprint for: {topic}. Objective: {objective}. Format: {fmt}; duration: {duration}s; audience: {audience}; tone: {tone}. Design a genuinely useful, original piece, not filler or a slideshow. Use web-research-ready claims, concrete examples, visual storytelling, scene variety, hook, escalation, payoff and CTA. Return ONLY JSON with creative_direction, hook_options, chapters, visual_language, sound_direction, editing_direction, quality_gates. chapters should be 5-12 objects with title,purpose,story_beat,visual_queries,proof_needed,approx_seconds.''' 
        try:
            r=model_fn({'messages':[{'role':'user','content':prompt}],'temperature':0.8})
            t=(r or {}).get('text') or (r or {}).get('answer') or ''
            x=_clean_json(t)
            if isinstance(x,dict) and x.get('chapters'): return x, (r or {}).get('provider','model')
        except Exception: pass
    return _default_strategy(topic,objective,fmt,audience,tone),'builtin'

def research_pack(topic, objective, limit=8):
    # Public-source research without pretending search results are generated by the model.
    from urllib.request import Request, urlopen
    from urllib.parse import quote
    sources=[]
    try:
        q=quote(topic)
        req=Request(f'https://en.wikipedia.org/w/api.php?action=query&format=json&generator=search&gsrsearch={q}&gsrlimit={limit}&prop=extracts|info&exintro=1&explaintext=1&inprop=url',headers={'User-Agent':'AI-Infinity/3608'})
        data=json.loads(urlopen(req,timeout=20).read().decode('utf-8','replace'))
        for p in (data.get('query',{}).get('pages',{}) or {}).values():
            sources.append({'title':p.get('title'),'url':p.get('fullurl'),'summary':p.get('extract','')[:4000],'source':'Wikipedia'})
    except Exception as e:
        sources.append({'source':'Wikipedia','error':str(e)[:200]})
    return {'topic':topic,'objective':objective,'sources':sources,'retrieved_at':time.time()}

def content_pack(topic, objective, fmt='long', duration=480, audience='general audience', tone='cinematic, intelligent, useful', model_fn=None):
    blueprint, provider=plan(topic,objective,fmt,duration,audience,tone,model_fn)
    research=research_pack(topic,objective)
    claims=[]
    for s in research.get('sources',[]):
        if s.get('title'): claims.append({'claim_source':s['title'],'url':s.get('url'),'use':'verify before publication'})
    return {'studio_version':'TARGET-2050.3608','status':'blueprint_ready','topic':topic,'objective':objective,'format':fmt,'duration_seconds':duration,'blueprint':blueprint,'research':research,'verification_queue':claims,'ai_provider':provider,'quality_gates':blueprint.get('quality_gates',[]),'self_upgrade':True,'truthful':True}

def learn(job_id, outcome, model_fn=None):
    c=_db(); row=c.execute('SELECT * FROM studio_jobs WHERE job_id=?',(job_id,)).fetchone()
    if not row: c.close(); return {'status':'unknown_job'}
    payload=json.loads(row['payload']); result=json.loads(row['result'] or '{}')
    score=float(outcome.get('quality_score',0) or 0)
    key=hashlib.sha256((payload.get('format','long')+'|'+payload.get('tone','')).encode()).hexdigest()[:16]
    old=c.execute('SELECT * FROM studio_skills WHERE skill_id=?',(key,)).fetchone()
    uses=(old['uses']+1) if old else 1; success=((old['success']*old['uses']+score)/uses) if old else score
    recipe=json.dumps({'format':payload.get('format'),'tone':payload.get('tone'),'lessons':outcome.get('lessons',[]),'last_job':job_id},ensure_ascii=False)
    c.execute('INSERT OR REPLACE INTO studio_skills VALUES(?,?,?,?,?,?,?)',(key,old['name'] if old else 'adaptive-content-workflow', (old['version']+1 if old else 1),recipe,success,uses,time.time()))
    c.execute('UPDATE studio_jobs SET updated=?, status=? WHERE job_id=?',(time.time(),'learned',job_id)); c.commit(); c.close()
    return {'status':'learned','skill_id':key,'skill_version':old['version']+1 if old else 1,'rolling_quality':round(success,4),'uses':uses,'truthful':True}

def register(app, model_fn=None):
    from fastapi import HTTPException
    from pydantic import BaseModel
    class StudioRequest(BaseModel):
        topic:str=''; objective:str=''; format:str='long'; duration:int|None=None; audience:str='general audience'; tone:str='cinematic, intelligent, useful'
    class LearnRequest(BaseModel):
        quality_score:float=0; lessons:list[str]=[]
    @app.get('/infinity/3608/health')
    def health():
        return {'status':'healthy','build':'TARGET-2050.3608-AI-CONTENT-STUDIO-OS','research':True,'creative_blueprints':True,'long_form':True,'short_form':True,'adaptive_learning':True,'skill_registry':True,'truthful':True}
    @app.post('/infinity/3608/studio')
    def studio(req:StudioRequest):
        if not (req.topic.strip() or req.objective.strip()): raise HTTPException(422,'topic or objective required')
        fmt='short' if req.format.lower() in {'short','shorts','reel','tiktok'} else 'long'
        duration=req.duration or (60 if fmt=='short' else 600)
        duration=max(20,min(duration,3600 if fmt=='long' else 180))
        x=content_pack(req.topic.strip() or req.objective,req.objective.strip(),fmt,duration,req.audience,req.tone,model_fn)
        jid=_uid('studio'); c=_db(); now=time.time(); c.execute('INSERT INTO studio_jobs VALUES(?,?,?,?,?,?)',(jid,'blueprint_ready',_json(req.model_dump()),_json(x),now,now)); c.commit(); c.close(); x['job_id']=jid
        return x
    @app.post('/infinity/3608/studio/{job_id}/learn')
    def learn_route(job_id:str,req:LearnRequest): return learn(job_id,req.model_dump(),model_fn)
    @app.get('/infinity/3608/skills')
    def skills():
        c=_db(); rows=[dict(x) for x in c.execute('SELECT skill_id,name,version,success,uses,updated FROM studio_skills ORDER BY updated DESC LIMIT 100')]; c.close(); return {'skills':rows,'self_upgradeable':True,'truthful':True}
